COUNTRY_NONE                =0x1        --无势力
COUNTRY_UNITED_SANCTUARY    =0x2        --王冠圣域
COUNTRY_ROYAL_PALADIN       =0x1002     --光辉骑士团
COUNTRY_ORACLE_THINK_TANK   =0x2002     --占卜魔法团
COUNTRY_ANGEL_FEATHER       =0x3002     --天使之羽
COUNTRY_SHADOW_PALADIN      =0x4002     --暗影骑士团
COUNTRY_GOLD_PALADIN        =0x5002     --黄金骑士团
COUNTRY_GENESIS             =0x6002     --创世
COUNTRY_DRAGON_EMPIRE       =0x4        --龙族帝国
COUNTRY_KAGERO              =0x1004     --阳炎
COUNTRY_NUBATAMA            =0x2004     --射干玉
COUNTRY_MURAKUMO            =0x3004     --太刀风
COUNTRY_TACHIKAZE           =0x4004     --丛云
COUNTRY_NARUKAMI            =0x5004     --鸣神
COUNTRY_BRANDT_GATE         =0x8        --布兰特之门
COUNTRY_NOVA_GRAPPLER       =0x1008     --搏击新星
COUNTRY_DIMENSION_POLICE    =0x2008     --次元警察
COUNTRY_LINK_JOKER          =0x3008     --链环傀儡
COUNTRY_DARK_ZONE           =0x10       --暗邦
COUNTRY_SPIKE_BROTHERS      =0x1010     --钢钉兄弟会
COUNTRY_DARK_IRREGULARS     =0x2010     --黑暗不法者
COUNTRY_PALE_MOON           =0x3010     --黯月
COUNTRY_GEAR_CHRONICLE      =0x4010     --齿轮编年史
COUNTRY_ZOO                 =0x20       --基元
COUNTRY_HUNDRED_GRUOP       =0x1020     --百群
COUNTRY_GREAT_NATURE        =0x2020     --大自然
COUNTRY_MEGACOLONY          =0x3020     --永生蜜酒
COUNTRY_NEO_NECTAR          =0x4020     --雄伟深蓝
COUNTRY_AQUA_FORCE          =0x5020     --苍海军势
COUNTRY_STOICHEIA           =0x40       --圣律诗院
COUNTRY_BERMUDA_TRIANGLE    =0x1040     --百慕大三角
COUNTRY_TOUKEN_RANBU        =0x80
COUNTRY_BANG_DREAM          =0x100
COUNTRY_MONSTER_STRIKE      =0x200
COUNTRY_YU_YU_HAKUSHO       =0x400
COUNTRY_THE_END_OF_THE_WORLDS_VALKYRIE=0x800